version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 3307:3306
    expose:
      - 3307 
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - container-link

  app:
    build: .
    container_name: app
    env_file: ./app.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3001:3000
    expose:
      - 3001 
    volumes:
      - ./src:/app
    working_dir: /app
    command:  npm run dev && docker exec -it app /bin/bash && npx sequelize-cli db:migrate
    networks:
      - container-link
    depends_on:
       mysql:
        condition: service_healthy

networks:
  default:
    external: 
      name: bridge
  container-link:
    name: docker.internal
    
volumes:
  mysqldata:

