version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 3307:3306
    expose:
      - 3307 
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
    networks:
      - container-link

  app:
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    build: .
    container_name: app
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3001:3000
    expose:
      - 3001 
    volumes:
      - ./src:/app
    working_dir: /app
    command:  npm run dev
    networks:
      - container-link
    depends_on:
       mysql:
        condition: service_healthy

networks:
  default:
    external: 
      name: bridge
  container-link:
    name: docker.internal
    
volumes:
  mysqldata:

