version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: attendance_db_container
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 3307:3306
    expose:
      - 3307 
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - container-link

  app:
    build: .
    container_name: attendance_app_container
    env_file: ./app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    stdin_open: true
    ports:
      - '3000:3000' 
    volumes:
      - ./src:/app
    working_dir: /app
    command: /bin/bash
    networks:
      - container-link
    depends_on:
      - mysql

networks:
  default:
    external: 
      name: bridge
  container-link:
    name: docker.internal
    
volumes:
  mysqldata:

